export default [
    'echo "hello word";',
    'print "stay home!"',
    'let person = "i don\'t know";',
    '__("i am a programmer and i have no life")',
    'System.out.println("stay home!")',
    'i\'m a programmer and doesn\'t mean i have to fix your pc',
    '{{ \'404! sob rice chairman churi kore niye geche\' }}',
    '"please stop writing useless code"',
    'quote("if you think the job is crap, wait\'til you see the pay");',
    'fmt.Print("work from home")',
    'my code works, i have no idea why',
    'exac("talk\'s cheap show me the code");',
    '__(\'a machine that converts coffee into code\', \'programmer\');',
    'echo \'code is poetry\';',
    'it\'s not a bug. it\'s an undocumented feature!',
    'my code doesn\'t work, i have no idea why',
    '1st rule of programming - if it works don\'t touch it',
    'keyboard not found! press any key to continue',
]